name: BukkitDebug
version: 0.0
description: Allows you to inspect running plugins (even ones you don't manage) and examine the server state.
author: Nickardson
authors: [Nickardson]

main: com.nickardson.bukkitdebug.BukkitDebug